id: P852E772D
initial_creation_type: input
source_metadata:
  title: Nonsectarianism Series
  language: bo
  description: 'Texts on the theme of nonsectarianism, impartiality or the absence
    of sectarian bias, a central ideal of the so-called nonsectarian or rimé (ris
    med) movement that blossomed in nineteenth-century Kham:'
  volume:
    5bb7a48c295e49949914e671c5deb8b6:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    741041d012b64a1791a7c872fd23c077:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    84f597dd19884231afdada5965fe0a0f:
      title: A Sun to Banish the Darkness of Wrong Views
      parent: Advice
    2676d943e34847869840ee7d35121b86:
      title: 'Opening the Door of Dharma: A Brief Discourse on the Essence of All
        Vehicles'
      parent: Advice
    cd7c0880185c4024a964db60cc42b521:
      title: Satirical Advice for the Four Schools
      parent: Advice
    f7c24b28f0c0437e9d2067c230ddb988:
      title: The Four Dharma Traditions of Tibet
      parent: Advice
    f1dc43040e184b1e83a6810ea534c6ce:
      title: 'The Sage''s Harmonious Song of Truth: A Prayer for the Flourishing of
        the Non-Sectarian Teachings of the Buddha'
      parent: Aspiration Prayers
    eb28439e8780412085f7623d94fbd8eb:
      title: 'All-Pervading Auspiciousness: An Aspiration for the Spread of the Teachings
        of the Eight Great Chariots of the Practice Lineage'
      parent: Aspiration Prayers
    2990bc639cf84a919a1cd443c86d414d:
      title: Aspiration for the Spread of the Teachings
      parent: Aspiration Prayers
    02fca598ecc440cbb433fd03747e412a:
      title: 'The Swift Fulfilment of Wishes: A Prayer of Aspiration'
      parent: Aspiration Prayers
    dd832a8d53534baaa6894d9a3f8d1ddd:
      title: Aspiration for the Spread of the Teachings of the Eight Chariots of the
        Practice Lineage
      parent: Aspiration Prayers
    39ed56f330dc49ae886d6007b4ddd61b:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    b46df03c3ed740dbafd89b19a4ebe8bc:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Prayers
    bae85b0c973448ebab81dddd0a7659b5:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    055c098e1df146de8522b006303d0e24:
      title: 'The Treasury of Blessings: A Prayer to Recall the Sublime Masters who
        Showed Great Kindness to the Land of Snows'
      parent: Prayers
    6801dcf752b64d0bba140718eec1c73f:
      title: 'The Flower of Faith: A Prayer to the Twenty-Five Founders of Buddha''s
        Teachings in Tibet'
      parent: Prayers
    35c74bc7078d4b21abcad4e653e08306:
      title: 'The Seed of Faith: A Prayer to the Sublime Ones'
      parent: Prayers
    58f3a70f60f74695a1755fb3d85e450b:
      title: Upon Hearing the Fluted Speech of Kunzang Dechen Tsomo, Queen Mother
        of Sikkim
      parent: Songs
created_at: '2022-03-01T04:51:37.224413'
last_modified_at: '2022-03-01T04:51:37.224416'
